-- Seed Data
-- 
-- Sample projects that make the portfolio look alive.
-- Run: php cli/pulse.php seed

INSERT OR IGNORE INTO projects (title, slug, description, long_description, tech_stack, category, thumbnail, live_url, source_url, featured, sort_order, status) VALUES
('Pulse', 'pulse', 'A custom PHP micro-framework with DI container, routing, middleware, and template engine — all hand-rolled.', 'Pulse is the framework that powers this very site. I built it from scratch because I wanted to understand every layer. It includes a PSR-4 autoloader, a fluent router with named routes and regex patterns, an onion-style middleware stack, a simple but powerful DI container with auto-wiring, a template engine supporting layout inheritance, an active-record-style model layer, and a custom validation system. No Composer dependencies for the core — just pure PHP. The admin panel, API endpoints, and CLI tool all run on top of this foundation. Every design decision was intentional, from the collection class to the error handler. This is my framework, my patterns, my signature.', 'PHP, SQLite, PDO, PSR-4', 'framework', '', '', '', 1, 1, 'published'),

('Vector Commerce', 'vector-commerce', 'Headless e-commerce API with real-time inventory, multi-currency support, and webhook integrations.', 'Vector Commerce started as a client project that needed something Shopify couldn''t do — real-time inventory sync across three warehouses with sub-second consistency. I built it as a headless API using PHP with a custom event dispatcher. Products, orders, customers, and webhooks all flow through a central event bus. The inventory system uses optimistic locking with retry logic, and currency conversion is handled by a background worker that polls exchange rates every 15 minutes. The API serves a Next.js storefront via REST endpoints, and the admin dashboard is a Vue SPA. Webhook delivery includes automatic retries with exponential backoff. Currently processing ~2k orders/day in production.', 'PHP, MySQL, Redis, Vue, Next.js, Docker', 'fullstack', '', '', '', 1, 2, 'published'),

('NetPulse CLI', 'netpulse-cli', 'A terminal-based network monitoring tool that visualizes latency, packet loss, and throughput in real-time.', 'NetPulse is a CLI tool I built because I was tired of opening browser dashboards just to check if my server was fine. It runs continuous ping tests, DNS lookups, and HTTP health checks against configurable endpoints. Results are displayed in a terminal UI built with ncurses-like character positioning — no actual ncurses dependency, I wrote the screen rendering myself using ANSI escape codes. It shows real-time sparkline graphs for latency, color-coded status indicators, and a log of incidents. The config is a single YAML file. You can set alert thresholds and it''ll ring your terminal bell when something crosses the line.', 'PHP, ANSI Terminal, Socket Programming', 'tool', '', '', '', 1, 3, 'published'),

('PixelForge', 'pixelforge', 'An image processing pipeline service with on-the-fly transformations, smart cropping, and CDN integration.', 'PixelForge is an image processing microservice that takes URLs or uploads and applies transformations via query parameters — resize, crop, rotate, filter, format conversion, and more. It uses GD and Imagick under the hood, with a caching layer that stores transformed images for subsequent requests. The smart crop feature uses edge detection to find the most interesting region of an image and crops to that area. I integrated it with a CDN so transformed images are served from edge nodes. The API is RESTful and returns images directly with proper caching headers. It processes about 50k image transformations per day for a content platform.', 'PHP, GD, Imagick, Redis, Nginx', 'api', '', '', '', 1, 4, 'published'),

('TaskFlow', 'taskflow', 'Kanban-style project management with real-time collaboration, WebSocket updates, and time tracking.', 'TaskFlow is a project management tool I built for a small team that was drowning in Trello limitations. It supports unlimited boards, customizable columns, card attachments, comments, due dates, labels, and time tracking. The real-time sync is powered by WebSockets — when anyone moves a card or adds a comment, all connected clients update instantly without polling. The time tracker runs as a separate timer per card, and a weekly report aggregates hours by project and team member. I also added keyboard shortcuts for power users (vim-style j/k navigation, x to archive, etc.). Authentication is JWT-based with refresh token rotation.', 'PHP, Ratchet (WebSocket), MySQL, JWT, Tailwind CSS', 'fullstack', '', '', '', 1, 5, 'published'),

('CSV Forge', 'csv-forge', 'A library for processing massive CSV files with minimal memory usage using generators and streaming.', 'CSV Forge solves a real problem: processing 2GB CSV files in PHP without running out of memory. Instead of loading the entire file into an array, it uses PHP generators to stream rows one at a time. It supports custom delimiters, enclosures, character encoding conversion, and chunked processing. The API is chainable — you can filter, map, and reduce rows in a pipeline without ever holding more than one row in memory. I also added a progress callback for long-running operations and a streaming JSON export mode. It''s used in production to process daily data feeds from multiple partners.', 'PHP, Generators, Streams', 'library', '', '', '', 1, 6, 'published'),

('CodeShot', 'codeshot', 'Automated screenshot service that captures web pages and generates social media preview images.', 'CodeShot is a service that takes a URL and generates a beautiful screenshot optimized for social media sharing — Open Graph images, Twitter cards, etc. It uses a headless Chromium instance managed by PHP to render pages at 1200x630 (OG standard), applies optional overlays (gradient, title, URL badge), and caches the result. The API accepts a URL and returns the image URL. I built a WordPress plugin that automatically generates OG images for every post using this service. It processes about 200 screenshots per day, with a median render time of 1.8 seconds.', 'PHP, Puppeteer, Node.js, Redis, Nginx', 'service', '', '', '', 0, 7, 'published'),

('QueryVault', 'queryvault', 'A SQL query organizer and snippet manager with syntax highlighting and connection testing.', 'QueryVault is a developer tool I built for myself and open-sourced. It stores SQL queries in categories with optional database connection configs. You can test queries directly from the UI (it connects to the DB and runs them), see execution time and result count, and share query snippets via URL. Syntax highlighting is done client-side using a lightweight JS library. The connection manager supports MySQL, PostgreSQL, and SQLite. Each query can be tagged for easy searching. It''s become my daily driver for anything database-related.', 'PHP, MySQL, PostgreSQL, SQLite, CodeMirror', 'tool', '', '', '', 0, 8, 'published');

-- ── seed some activity logs for visual appeal ───────────
INSERT OR IGNORE INTO activity_logs (event_type, description, metadata, ip_address, created_at) VALUES
('deploy', 'Initial deployment of Pulse', '{"version": "1.0.0"}', '127.0.0.1', datetime('now', '-30 days')),
('create_project', 'Added project: Vector Commerce', '{"project_id": 2}', '127.0.0.1', datetime('now', '-25 days')),
('visit', 'Homepage visit spike detected', '{"count": 142}', '192.168.1.1', datetime('now', '-20 days')),
('contact', 'New inquiry about freelance work', '{"email": "client@example.com"}', '10.0.0.1', datetime('now', '-15 days')),
('deploy', 'Updated to v1.2.0 with admin panel', '{"version": "1.2.0", "files_changed": 23}', '127.0.0.1', datetime('now', '-10 days')),
('create_project', 'Added project: TaskFlow', '{"project_id": 5}', '127.0.0.1', datetime('now', '-7 days')),
('visit', 'Project page: Pulse viewed 50 times today', '{"path": "/projects/pulse"}', '203.0.113.1', datetime('now', '-3 days')),
('deploy', 'Performance optimization pass', '{"improvement": "40% faster page load"}', '127.0.0.1', datetime('now', '-1 days')),
('create_project', 'Added project: QueryVault', '{"project_id": 8}', '127.0.0.1', datetime('now', '-12 hours')),
('visit', 'Contact page visited from Twitter referral', '{"referrer": "twitter.com"}', '198.51.100.1', datetime('now', '-2 hours'));

-- ── seed some contact messages ────────────────────────────
INSERT OR IGNORE INTO contact_messages (name, email, subject, message, ip_address, is_read) VALUES
('Sarah Chen', 'sarah@startup.io', 'Freelance Project Inquiry', 'Hey, I saw your portfolio and I''m really impressed with the Vector Commerce project. We''re building something similar and could use your expertise. Would you be available for a call next week?', '10.0.0.2', 0),
('Marcus Johnson', 'marcus@devagency.com', 'Speaking Opportunity', 'We''re organizing a PHP meetup and would love to have you talk about building custom frameworks. Your Pulse project is exactly the kind of thing our community would love to hear about.', '172.16.0.1', 0),
('Emily Rodriguez', 'emily.r@techcorp.com', 'Job Opportunity', 'Hi! I''m a tech recruiter at TechCorp. We have a senior PHP developer position open and your skillset looks like a perfect match. Would you be open to discussing?', '192.168.2.5', 1);